import "./global.scss";

import { AnimatedLayout } from "../components";
import { AuthProvider } from "./authProvider";

export const metadata = {
  title: "Roboskills 2026 | مسابقات بینلمللی روبوسکیل",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
